//! Rust mirrors of EQ wire structs, generated by `bindgen` against
//! `showeq-daemon/src/everquest.h`. Adding more structs is a one-line
//! `.allowlist_type(...)` edit in `build.rs`.
//!
//! Bindgen's bitfield getters mask but don't always sign-extend the
//! way the C handler reads them (specifically: `int64_t y:19` needs
//! arithmetic-right-shift sign extension after masking). The
//! [`sign_extend`] helper covers the EQ-specific bit widths we hit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(unnecessary_transmutes)] // bindgen 0.71 emits these in bitfield accessors

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// Sign-extend the low `bits` of `v` into an `i32`. Used to recover the
/// sign of EQ's narrow signed bitfields (e.g. position coordinates are
/// 19-bit signed values stored in a packed `int64_t`).
#[inline]
pub fn sign_extend(v: u32, bits: u32) -> i32 {
    debug_assert!(bits > 0 && bits <= 32);
    let shift = 32 - bits;
    ((v << shift) as i32) >> shift
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sign_extend_19_bit() {
        assert_eq!(sign_extend(0, 19), 0);
        assert_eq!(sign_extend(1, 19), 1);
        assert_eq!(sign_extend(0x3_FFFF, 19), 0x3_FFFF);
        assert_eq!(sign_extend(0x4_0000, 19), -262_144);
        assert_eq!(sign_extend(0x7_FFFF, 19), -1);
    }

    #[test]
    fn spawn_position_update_layout() {
        // sanity: bindgen-generated struct must match the 14-byte payload
        // the EQ wire format gives us.
        assert_eq!(std::mem::size_of::<spawnPositionUpdate>(), 14);
    }
}
