[workspace]
resolver = "2"
members = ["seq-decode", "seq-bridge", "seq-eqstructs"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-2.0"
authors = ["ShowEQ Developers"]
rust-version = "1.75"

[workspace.dependencies]
cxx = "1"
cxx-build = "1"
thiserror = "2"
seq-decode = { path = "seq-decode" }
seq-eqstructs = { path = "seq-eqstructs" }

[profile.release]
lto = "thin"
codegen-units = 1

[workspace.lints.rust]
warnings = "deny"
