//! Parser for `OP_MobUpdate` — payload `spawnPositionUpdate`, 14 bytes.
//!
//! The struct layout (size, field offsets, bitfield positions) comes
//! from `seq_eqstructs_live::spawnPositionUpdate`, generated by bindgen
//! against `showeq-daemon/src/everquest.h`. Bindgen's bitfield getters
//! mask but don't sign-extend signed bitfields, so the 19-bit signed
//! position fields go through [`sign_extend`] before the daemon's
//! `>> 3` fixed-point conversion (1/8-unit → integer game world).
//! Heading is 12-bit unsigned and passed through unchanged.

use seq_eqstructs_live::{sign_extend, spawnPositionUpdate};
use thiserror::Error;

pub const PAYLOAD_LEN: usize = std::mem::size_of::<spawnPositionUpdate>();

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MobUpdate {
    pub spawn_id: u16,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub heading: u16,
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum ParseError {
    #[error("expected {PAYLOAD_LEN} bytes, got {0}")]
    BadLength(usize),
}

pub fn parse_mob_update(bytes: &[u8]) -> Result<MobUpdate, ParseError> {
    if bytes.len() != PAYLOAD_LEN {
        return Err(ParseError::BadLength(bytes.len()));
    }

    // SAFETY: spawnPositionUpdate is #[repr(C, packed)] POD, length checked above.
    let raw: spawnPositionUpdate =
        unsafe { std::ptr::read_unaligned(bytes.as_ptr() as *const spawnPositionUpdate) };

    let spawn_id = unsafe { std::ptr::addr_of!(raw.spawnId).read_unaligned() } as u16;
    let y = sign_extend(raw.y() as u32, 19) >> 3;
    let z = sign_extend(raw.z() as u32, 19) >> 3;
    let x = sign_extend(raw.x() as u32, 19) >> 3;
    let heading = raw.heading() as u16;

    Ok(MobUpdate { spawn_id, x, y, z, heading })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_wrong_length() {
        assert_eq!(parse_mob_update(&[]), Err(ParseError::BadLength(0)));
        assert_eq!(parse_mob_update(&[0; 13]), Err(ParseError::BadLength(13)));
        assert_eq!(parse_mob_update(&[0; 15]), Err(ParseError::BadLength(15)));
    }

    #[test]
    fn all_zero_payload() {
        assert_eq!(
            parse_mob_update(&[0; 14]).unwrap(),
            MobUpdate { spawn_id: 0, x: 0, y: 0, z: 0, heading: 0 },
        );
    }

    #[test]
    fn sign_extension_negative_x() {
        // x bitfield occupies bits 45..64 of the 80-bit packed unit
        // starting at byte offset 4. Set x = 0x4_0000 (the 19-bit signed
        // minimum, == -262144 before the >>3) and everything else to 0.
        let mut bytes = [0u8; 14];
        // Word at offset 4..12: x in bits 45..64.
        let bf: u64 = 0x4_0000u64 << 45;
        bytes[4..12].copy_from_slice(&bf.to_le_bytes());
        let parsed = parse_mob_update(&bytes).unwrap();
        assert_eq!(parsed.x, -262_144 >> 3);
        assert_eq!(parsed.y, 0);
        assert_eq!(parsed.z, 0);
    }

    #[test]
    fn heading_mask_is_12_bit() {
        // heading occupies bits 64..76 of the same 80-bit unit (= bits 0..12
        // of the 16-bit word at byte offset 12). All-ones in those bits
        // should yield 0x0FFF; the 4 high bits (unused2) are discarded.
        let mut bytes = [0u8; 14];
        bytes[12] = 0xFF;
        bytes[13] = 0xFF;
        let parsed = parse_mob_update(&bytes).unwrap();
        assert_eq!(parsed.heading, 0x0FFF);
    }
}
