//! Parser for `OP_MobUpdate` — payload `spawnPositionUpdate`, 14 bytes.
//!
//! The struct layout (size, field offsets, bitfield positions) comes
//! from `crate::eqstructs::spawnPositionUpdate`, generated by bindgen
//! against `showeq-daemon/src/everquest.h`. Bindgen's bitfield getters
//! mask but don't sign-extend signed bitfields, so the 19-bit signed
//! position fields go through [`sign_extend`] before the daemon's
//! `>> 3` fixed-point conversion (1/8-unit → integer game world).
//! Heading is 12-bit unsigned and passed through unchanged.

use crate::eqstructs::{sign_extend, spawnPositionUpdate};
use thiserror::Error;

pub const PAYLOAD_LEN: usize = std::mem::size_of::<spawnPositionUpdate>();

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct MobUpdate {
    pub spawn_id: u16,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub heading: u16,
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum ParseError {
    #[error("expected {PAYLOAD_LEN} bytes, got {0}")]
    BadLength(usize),
}

pub fn parse_mob_update(bytes: &[u8]) -> Result<MobUpdate, ParseError> {
    if bytes.len() != PAYLOAD_LEN {
        return Err(ParseError::BadLength(bytes.len()));
    }

    // 2026-07-28: read the packed coordinates explicitly rather than through the
    // generated binding, whose bitfield positions are the PRE-patch ones — they
    // put x where y now lives and account for no gap, so the fields landed
    // misaligned and produced trajectories that jumped by thousands of units.
    // Layout per upstream's spawnPositionUpdateEQL (legends 7612d72), a 64-bit
    // packed unit at byte 4:
    //     x  bits  0..18
    //     z  bits 19..37
    //     -  bits 38..44   (7-bit gap — omitting it is what shifted y)
    //     y  bits 45..63
    let spawn_id = u16::from_le_bytes([bytes[0], bytes[1]]);
    let mut w = [0u8; 8];
    w.copy_from_slice(&bytes[4..12]);
    let packed = u64::from_le_bytes(w);
    let field = |shift: u32| sign_extend(((packed >> shift) & 0x7FFFF) as u32, 19) >> 3;
    let x = field(0);
    let z = field(19);
    let y = field(45);
    let heading = u16::from_le_bytes([bytes[12], bytes[13]]) & 0x0FFF;

    Ok(MobUpdate { spawn_id, x, y, z, heading })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_wrong_length() {
        assert_eq!(parse_mob_update(&[]), Err(ParseError::BadLength(0)));
        assert_eq!(parse_mob_update(&[0; 13]), Err(ParseError::BadLength(13)));
        assert_eq!(parse_mob_update(&[0; 15]), Err(ParseError::BadLength(15)));
    }

    #[test]
    fn all_zero_payload() {
        assert_eq!(
            parse_mob_update(&[0; 14]).unwrap(),
            MobUpdate { spawn_id: 0, x: 0, y: 0, z: 0, heading: 0 },
        );
    }

    #[test]
    fn sign_extension_negative_x() {
        // x is bits 0..18 of the 64-bit packed unit at byte 4. Set it to
        // 0x4_0000 (the 19-bit signed minimum, -262144 before the >>3).
        let mut bytes = [0u8; 14];
        let bf: u64 = 0x4_0000u64;
        bytes[4..12].copy_from_slice(&bf.to_le_bytes());
        let m = parse_mob_update(&bytes).unwrap();
        assert_eq!(m.x, -32768);
        assert_eq!(m.y, 0);
        assert_eq!(m.z, 0);
    }

    // The gap between z and y is what the pre-patch binding omitted; pin each
    // coordinate at its own offset so a future regeneration cannot re-shift them.
    #[test]
    fn each_coordinate_reads_from_its_own_field() {
        let mut bytes = [0u8; 14];
        let bf: u64 = (800u64 << 0) | (16u64 << 19) | (2400u64 << 45);
        bytes[4..12].copy_from_slice(&bf.to_le_bytes());
        let m = parse_mob_update(&bytes).unwrap();
        assert_eq!(m.x, 100); // 800 >> 3
        assert_eq!(m.z, 2); //  16 >> 3
        assert_eq!(m.y, 300); // 2400 >> 3
    }

}
