[package]
name = "seq-eqstructs"
description = "bindgen-generated Rust mirrors of showeq-daemon/src/everquest.h."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[build-dependencies]
bindgen.workspace = true

[lints]
workspace = true
